name: portfolio
description: A new Flutter project.

version: 1.0.0+1


environment:
  sdk: ">=2.5.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^8.5.0
  google_fonts: ^0.3.9


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/placelytics/