List<String> uniCourses = [
  'Programming 1 - Fundamentals',
  'Physics 1',
  'Linear Algebra with Geometry',
  'Introduction to Formal Logic and Set Theory',
  'Electronic Principles',
  'Calculus 1',
  'UNIX Fundamentals',
  'Programming 2 - Object Oriented',
  'Physics 2',
  'Introduction to Digital Systems',
  'Discrete Mathematics 1',
  'Calculus 2',
  'Communication Skills',
  'Social Communication',
  'Programming 3 - Advanced',
  'Operating Systems 1',
  'Intellectual Property Law',
  'Discrete Mathematics 2',
  'Differential Equations',
  'Data Transmission',
  'Algorithms and Data Structures',
  'Social and Professional Aspects in Computer Science',
  'Programming in Graphical Environment',
  'Probability',
  'Operating Systems 2',
  'Object Oriented Design',
  'Numerical Methods 1',
  'Databases',
  'Software Engineering 1',
  'Numerical Methods 2',
  'Creating Web Applications with .NET Framework',
  'Computer Statistics',
  'Computer Networks',
  'Automata Theory and Formal Languages',
  'Android Application Development',
  'Software Engineering 2',
  'Machine Learning Workshop',
  'Introduction to Natural Language Processing',
  'Introduction to Embedded Systems',
  'Computer Graphics 1',
  'Artificial Intelligence Fundamentals',
  'Agent Systems and Applications',
  'Introduction to Image Processing and Computer Vision',
  'Group Project',
  'Algorithms and Computability',
]..sort();